org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=20
unityProjectPath=C:/Users/User/Downloads/Ndimthandile_Mkalipi_08HA2600763_ HFGE1181_SA1
unity.projectPath=C:/Users/User/Downloads/Ndimthandile_Mkalipi_08HA2600763_ HFGE1181_SA1
unity.debugSymbolLevel=symbol_table
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=34
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.Boston.NotSpaceInvader
unity.abiFilters=armeabi-v7a
unity.versionCode=1
unity.versionName=1.0
unity.namespace=com.Boston.NotSpaceInvader
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.63f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.63f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.63f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never